package com.example.effectivemobiletestwork.subscriptions.ui

import com.example.effectivemobiletestwork.base.BaseFragment
import com.example.effectivemobiletestwork.databinding.FragmentSubscriptionsBinding

class SubscriptionsFragment : BaseFragment<FragmentSubscriptionsBinding>(FragmentSubscriptionsBinding::inflate)