package com.example.effectivemobiletestwork.avia.ui.hotTickets

import com.example.effectivemobiletestwork.base.BaseFragment
import com.example.effectivemobiletestwork.databinding.FragmentHotTicketsBinding

class HotTicketsFragment : BaseFragment<FragmentHotTicketsBinding>(FragmentHotTicketsBinding::inflate)